/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellWarehouseRouteImport } from './routes/_shell/warehouse'
import { Route as ShellSecurityRouteImport } from './routes/_shell/security'
import { Route as ShellProfileRouteImport } from './routes/_shell/profile'
import { Route as ShellOverviewRouteImport } from './routes/_shell/overview'
import { Route as ShellNotificationsRouteImport } from './routes/_shell/notifications'
import { Route as ShellLogisticsRouteImport } from './routes/_shell/logistics'
import { Route as ShellFinanceRouteImport } from './routes/_shell/finance'
import { Route as ShellWarehouseIndexRouteImport } from './routes/_shell/warehouse/index'
import { Route as ShellSecurityIndexRouteImport } from './routes/_shell/security/index'
import { Route as ShellLogisticsIndexRouteImport } from './routes/_shell/logistics/index'
import { Route as ShellFinanceIndexRouteImport } from './routes/_shell/finance/index'
import { Route as ShellWarehouseStockOverviewRouteImport } from './routes/_shell/warehouse/stock-overview'
import { Route as ShellWarehouseProductionRouteImport } from './routes/_shell/warehouse/production'
import { Route as ShellWarehouseGrnRouteImport } from './routes/_shell/warehouse/grn'
import { Route as ShellWarehouseBinCardRouteImport } from './routes/_shell/warehouse/bin-card'
import { Route as ShellWarehouseAlertsRouteImport } from './routes/_shell/warehouse/alerts'
import { Route as ShellSettingsUserManagementRouteImport } from './routes/_shell/settings/user-management'
import { Route as ShellSettingsStaffRouteImport } from './routes/_shell/settings/staff'
import { Route as ShellSettingsRbacRouteImport } from './routes/_shell/settings/rbac'
import { Route as ShellSettingsProfileRouteImport } from './routes/_shell/settings/profile'
import { Route as ShellSettingsOrgSettingsRouteImport } from './routes/_shell/settings/org-settings'
import { Route as ShellSettingsBranchesRouteImport } from './routes/_shell/settings/branches'
import { Route as ShellSecurityVisitorLogRouteImport } from './routes/_shell/security/visitor-log'
import { Route as ShellSecuritySuppliersRouteImport } from './routes/_shell/security/suppliers'
import { Route as ShellSecurityStaffMovementRouteImport } from './routes/_shell/security/staff-movement'
import { Route as ShellSecurityStaffAttendanceRouteImport } from './routes/_shell/security/staff-attendance'
import { Route as ShellSecurityMotorcycleLogRouteImport } from './routes/_shell/security/motorcycle-log'
import { Route as ShellSecurityMaterialsHandoffRouteImport } from './routes/_shell/security/materials-handoff'
import { Route as ShellSecurityLogsRouteImport } from './routes/_shell/security/logs'
import { Route as ShellSecurityLightTokenRouteImport } from './routes/_shell/security/light-token'
import { Route as ShellSecurityLabourersLogRouteImport } from './routes/_shell/security/labourers-log'
import { Route as ShellSecurityItemBoughtRouteImport } from './routes/_shell/security/item-bought'
import { Route as ShellSecurityGateLogRouteImport } from './routes/_shell/security/gate-log'
import { Route as ShellSecurityDispatchRouteImport } from './routes/_shell/security/dispatch'
import { Route as ShellSecurityAttendanceScannerRouteImport } from './routes/_shell/security/attendance-scanner'
import { Route as ShellLogisticsWaybillsRouteImport } from './routes/_shell/logistics/waybills'
import { Route as ShellLogisticsTripsRouteImport } from './routes/_shell/logistics/trips'
import { Route as ShellLogisticsMaintenanceRouteImport } from './routes/_shell/logistics/maintenance'
import { Route as ShellLogisticsFleetRouteImport } from './routes/_shell/logistics/fleet'
import { Route as ShellLogisticsDriversRouteImport } from './routes/_shell/logistics/drivers'
import { Route as ShellFinanceSupplierPaymentsRouteImport } from './routes/_shell/finance/supplier-payments'
import { Route as ShellFinanceSalesRouteImport } from './routes/_shell/finance/sales'
import { Route as ShellFinancePayrollRouteImport } from './routes/_shell/finance/payroll'
import { Route as ShellFinanceOverviewRouteImport } from './routes/_shell/finance/overview'
import { Route as ShellFinanceInvoicesRouteImport } from './routes/_shell/finance/invoices'
import { Route as ShellFinanceExpensesRouteImport } from './routes/_shell/finance/expenses'
import { Route as ShellCeoReportsRouteImport } from './routes/_shell/ceo/reports'
import { Route as ShellCeoOverviewRouteImport } from './routes/_shell/ceo/overview'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellWarehouseRoute = ShellWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSecurityRoute = ShellSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProfileRoute = ShellProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOverviewRoute = ShellOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNotificationsRoute = ShellNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ShellRoute,
} as any)
const ShellLogisticsRoute = ShellLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellFinanceRoute = ShellFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWarehouseIndexRoute = ShellWarehouseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellWarehouseRoute,
} as any)
const ShellSecurityIndexRoute = ShellSecurityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellLogisticsIndexRoute = ShellLogisticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellLogisticsRoute,
} as any)
const ShellFinanceIndexRoute = ShellFinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellFinanceRoute,
} as any)
const ShellWarehouseStockOverviewRoute =
  ShellWarehouseStockOverviewRouteImport.update({
    id: '/stock-overview',
    path: '/stock-overview',
    getParentRoute: () => ShellWarehouseRoute,
  } as any)
const ShellWarehouseProductionRoute =
  ShellWarehouseProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => ShellWarehouseRoute,
  } as any)
const ShellWarehouseGrnRoute = ShellWarehouseGrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => ShellWarehouseRoute,
} as any)
const ShellWarehouseBinCardRoute = ShellWarehouseBinCardRouteImport.update({
  id: '/bin-card',
  path: '/bin-card',
  getParentRoute: () => ShellWarehouseRoute,
} as any)
const ShellWarehouseAlertsRoute = ShellWarehouseAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ShellWarehouseRoute,
} as any)
const ShellSettingsUserManagementRoute =
  ShellSettingsUserManagementRouteImport.update({
    id: '/settings/user-management',
    path: '/settings/user-management',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellSettingsStaffRoute = ShellSettingsStaffRouteImport.update({
  id: '/settings/staff',
  path: '/settings/staff',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRbacRoute = ShellSettingsRbacRouteImport.update({
  id: '/settings/rbac',
  path: '/settings/rbac',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsProfileRoute = ShellSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsOrgSettingsRoute =
  ShellSettingsOrgSettingsRouteImport.update({
    id: '/settings/org-settings',
    path: '/settings/org-settings',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellSettingsBranchesRoute = ShellSettingsBranchesRouteImport.update({
  id: '/settings/branches',
  path: '/settings/branches',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSecurityVisitorLogRoute = ShellSecurityVisitorLogRouteImport.update({
  id: '/visitor-log',
  path: '/visitor-log',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecuritySuppliersRoute = ShellSecuritySuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecurityStaffMovementRoute =
  ShellSecurityStaffMovementRouteImport.update({
    id: '/staff-movement',
    path: '/staff-movement',
    getParentRoute: () => ShellSecurityRoute,
  } as any)
const ShellSecurityStaffAttendanceRoute =
  ShellSecurityStaffAttendanceRouteImport.update({
    id: '/staff-attendance',
    path: '/staff-attendance',
    getParentRoute: () => ShellSecurityRoute,
  } as any)
const ShellSecurityMotorcycleLogRoute =
  ShellSecurityMotorcycleLogRouteImport.update({
    id: '/motorcycle-log',
    path: '/motorcycle-log',
    getParentRoute: () => ShellSecurityRoute,
  } as any)
const ShellSecurityMaterialsHandoffRoute =
  ShellSecurityMaterialsHandoffRouteImport.update({
    id: '/materials-handoff',
    path: '/materials-handoff',
    getParentRoute: () => ShellSecurityRoute,
  } as any)
const ShellSecurityLogsRoute = ShellSecurityLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecurityLightTokenRoute = ShellSecurityLightTokenRouteImport.update({
  id: '/light-token',
  path: '/light-token',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecurityLabourersLogRoute =
  ShellSecurityLabourersLogRouteImport.update({
    id: '/labourers-log',
    path: '/labourers-log',
    getParentRoute: () => ShellSecurityRoute,
  } as any)
const ShellSecurityItemBoughtRoute = ShellSecurityItemBoughtRouteImport.update({
  id: '/item-bought',
  path: '/item-bought',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecurityGateLogRoute = ShellSecurityGateLogRouteImport.update({
  id: '/gate-log',
  path: '/gate-log',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecurityDispatchRoute = ShellSecurityDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => ShellSecurityRoute,
} as any)
const ShellSecurityAttendanceScannerRoute =
  ShellSecurityAttendanceScannerRouteImport.update({
    id: '/attendance-scanner',
    path: '/attendance-scanner',
    getParentRoute: () => ShellSecurityRoute,
  } as any)
const ShellLogisticsWaybillsRoute = ShellLogisticsWaybillsRouteImport.update({
  id: '/waybills',
  path: '/waybills',
  getParentRoute: () => ShellLogisticsRoute,
} as any)
const ShellLogisticsTripsRoute = ShellLogisticsTripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => ShellLogisticsRoute,
} as any)
const ShellLogisticsMaintenanceRoute =
  ShellLogisticsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => ShellLogisticsRoute,
  } as any)
const ShellLogisticsFleetRoute = ShellLogisticsFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => ShellLogisticsRoute,
} as any)
const ShellLogisticsDriversRoute = ShellLogisticsDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => ShellLogisticsRoute,
} as any)
const ShellFinanceSupplierPaymentsRoute =
  ShellFinanceSupplierPaymentsRouteImport.update({
    id: '/supplier-payments',
    path: '/supplier-payments',
    getParentRoute: () => ShellFinanceRoute,
  } as any)
const ShellFinanceSalesRoute = ShellFinanceSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ShellFinanceRoute,
} as any)
const ShellFinancePayrollRoute = ShellFinancePayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => ShellFinanceRoute,
} as any)
const ShellFinanceOverviewRoute = ShellFinanceOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ShellFinanceRoute,
} as any).lazy(() =>
  import('./routes/_shell/finance/overview.lazy').then((d) => d.Route),
)
const ShellFinanceInvoicesRoute = ShellFinanceInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => ShellFinanceRoute,
} as any)
const ShellFinanceExpensesRoute = ShellFinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => ShellFinanceRoute,
} as any)
const ShellCeoReportsRoute = ShellCeoReportsRouteImport.update({
  id: '/ceo/reports',
  path: '/ceo/reports',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/ceo/reports.lazy').then((d) => d.Route),
)
const ShellCeoOverviewRoute = ShellCeoOverviewRouteImport.update({
  id: '/ceo/overview',
  path: '/ceo/overview',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/finance': typeof ShellFinanceRouteWithChildren
  '/logistics': typeof ShellLogisticsRouteWithChildren
  '/notifications': typeof ShellNotificationsRoute
  '/overview': typeof ShellOverviewRoute
  '/profile': typeof ShellProfileRoute
  '/security': typeof ShellSecurityRouteWithChildren
  '/warehouse': typeof ShellWarehouseRouteWithChildren
  '/ceo/overview': typeof ShellCeoOverviewRoute
  '/ceo/reports': typeof ShellCeoReportsRoute
  '/finance/expenses': typeof ShellFinanceExpensesRoute
  '/finance/invoices': typeof ShellFinanceInvoicesRoute
  '/finance/overview': typeof ShellFinanceOverviewRoute
  '/finance/payroll': typeof ShellFinancePayrollRoute
  '/finance/sales': typeof ShellFinanceSalesRoute
  '/finance/supplier-payments': typeof ShellFinanceSupplierPaymentsRoute
  '/logistics/drivers': typeof ShellLogisticsDriversRoute
  '/logistics/fleet': typeof ShellLogisticsFleetRoute
  '/logistics/maintenance': typeof ShellLogisticsMaintenanceRoute
  '/logistics/trips': typeof ShellLogisticsTripsRoute
  '/logistics/waybills': typeof ShellLogisticsWaybillsRoute
  '/security/attendance-scanner': typeof ShellSecurityAttendanceScannerRoute
  '/security/dispatch': typeof ShellSecurityDispatchRoute
  '/security/gate-log': typeof ShellSecurityGateLogRoute
  '/security/item-bought': typeof ShellSecurityItemBoughtRoute
  '/security/labourers-log': typeof ShellSecurityLabourersLogRoute
  '/security/light-token': typeof ShellSecurityLightTokenRoute
  '/security/logs': typeof ShellSecurityLogsRoute
  '/security/materials-handoff': typeof ShellSecurityMaterialsHandoffRoute
  '/security/motorcycle-log': typeof ShellSecurityMotorcycleLogRoute
  '/security/staff-attendance': typeof ShellSecurityStaffAttendanceRoute
  '/security/staff-movement': typeof ShellSecurityStaffMovementRoute
  '/security/suppliers': typeof ShellSecuritySuppliersRoute
  '/security/visitor-log': typeof ShellSecurityVisitorLogRoute
  '/settings/branches': typeof ShellSettingsBranchesRoute
  '/settings/org-settings': typeof ShellSettingsOrgSettingsRoute
  '/settings/profile': typeof ShellSettingsProfileRoute
  '/settings/rbac': typeof ShellSettingsRbacRoute
  '/settings/staff': typeof ShellSettingsStaffRoute
  '/settings/user-management': typeof ShellSettingsUserManagementRoute
  '/warehouse/alerts': typeof ShellWarehouseAlertsRoute
  '/warehouse/bin-card': typeof ShellWarehouseBinCardRoute
  '/warehouse/grn': typeof ShellWarehouseGrnRoute
  '/warehouse/production': typeof ShellWarehouseProductionRoute
  '/warehouse/stock-overview': typeof ShellWarehouseStockOverviewRoute
  '/finance/': typeof ShellFinanceIndexRoute
  '/logistics/': typeof ShellLogisticsIndexRoute
  '/security/': typeof ShellSecurityIndexRoute
  '/warehouse/': typeof ShellWarehouseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/notifications': typeof ShellNotificationsRoute
  '/overview': typeof ShellOverviewRoute
  '/profile': typeof ShellProfileRoute
  '/ceo/overview': typeof ShellCeoOverviewRoute
  '/ceo/reports': typeof ShellCeoReportsRoute
  '/finance/expenses': typeof ShellFinanceExpensesRoute
  '/finance/invoices': typeof ShellFinanceInvoicesRoute
  '/finance/overview': typeof ShellFinanceOverviewRoute
  '/finance/payroll': typeof ShellFinancePayrollRoute
  '/finance/sales': typeof ShellFinanceSalesRoute
  '/finance/supplier-payments': typeof ShellFinanceSupplierPaymentsRoute
  '/logistics/drivers': typeof ShellLogisticsDriversRoute
  '/logistics/fleet': typeof ShellLogisticsFleetRoute
  '/logistics/maintenance': typeof ShellLogisticsMaintenanceRoute
  '/logistics/trips': typeof ShellLogisticsTripsRoute
  '/logistics/waybills': typeof ShellLogisticsWaybillsRoute
  '/security/attendance-scanner': typeof ShellSecurityAttendanceScannerRoute
  '/security/dispatch': typeof ShellSecurityDispatchRoute
  '/security/gate-log': typeof ShellSecurityGateLogRoute
  '/security/item-bought': typeof ShellSecurityItemBoughtRoute
  '/security/labourers-log': typeof ShellSecurityLabourersLogRoute
  '/security/light-token': typeof ShellSecurityLightTokenRoute
  '/security/logs': typeof ShellSecurityLogsRoute
  '/security/materials-handoff': typeof ShellSecurityMaterialsHandoffRoute
  '/security/motorcycle-log': typeof ShellSecurityMotorcycleLogRoute
  '/security/staff-attendance': typeof ShellSecurityStaffAttendanceRoute
  '/security/staff-movement': typeof ShellSecurityStaffMovementRoute
  '/security/suppliers': typeof ShellSecuritySuppliersRoute
  '/security/visitor-log': typeof ShellSecurityVisitorLogRoute
  '/settings/branches': typeof ShellSettingsBranchesRoute
  '/settings/org-settings': typeof ShellSettingsOrgSettingsRoute
  '/settings/profile': typeof ShellSettingsProfileRoute
  '/settings/rbac': typeof ShellSettingsRbacRoute
  '/settings/staff': typeof ShellSettingsStaffRoute
  '/settings/user-management': typeof ShellSettingsUserManagementRoute
  '/warehouse/alerts': typeof ShellWarehouseAlertsRoute
  '/warehouse/bin-card': typeof ShellWarehouseBinCardRoute
  '/warehouse/grn': typeof ShellWarehouseGrnRoute
  '/warehouse/production': typeof ShellWarehouseProductionRoute
  '/warehouse/stock-overview': typeof ShellWarehouseStockOverviewRoute
  '/finance': typeof ShellFinanceIndexRoute
  '/logistics': typeof ShellLogisticsIndexRoute
  '/security': typeof ShellSecurityIndexRoute
  '/warehouse': typeof ShellWarehouseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_shell': typeof ShellRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_shell/finance': typeof ShellFinanceRouteWithChildren
  '/_shell/logistics': typeof ShellLogisticsRouteWithChildren
  '/_shell/notifications': typeof ShellNotificationsRoute
  '/_shell/overview': typeof ShellOverviewRoute
  '/_shell/profile': typeof ShellProfileRoute
  '/_shell/security': typeof ShellSecurityRouteWithChildren
  '/_shell/warehouse': typeof ShellWarehouseRouteWithChildren
  '/_shell/ceo/overview': typeof ShellCeoOverviewRoute
  '/_shell/ceo/reports': typeof ShellCeoReportsRoute
  '/_shell/finance/expenses': typeof ShellFinanceExpensesRoute
  '/_shell/finance/invoices': typeof ShellFinanceInvoicesRoute
  '/_shell/finance/overview': typeof ShellFinanceOverviewRoute
  '/_shell/finance/payroll': typeof ShellFinancePayrollRoute
  '/_shell/finance/sales': typeof ShellFinanceSalesRoute
  '/_shell/finance/supplier-payments': typeof ShellFinanceSupplierPaymentsRoute
  '/_shell/logistics/drivers': typeof ShellLogisticsDriversRoute
  '/_shell/logistics/fleet': typeof ShellLogisticsFleetRoute
  '/_shell/logistics/maintenance': typeof ShellLogisticsMaintenanceRoute
  '/_shell/logistics/trips': typeof ShellLogisticsTripsRoute
  '/_shell/logistics/waybills': typeof ShellLogisticsWaybillsRoute
  '/_shell/security/attendance-scanner': typeof ShellSecurityAttendanceScannerRoute
  '/_shell/security/dispatch': typeof ShellSecurityDispatchRoute
  '/_shell/security/gate-log': typeof ShellSecurityGateLogRoute
  '/_shell/security/item-bought': typeof ShellSecurityItemBoughtRoute
  '/_shell/security/labourers-log': typeof ShellSecurityLabourersLogRoute
  '/_shell/security/light-token': typeof ShellSecurityLightTokenRoute
  '/_shell/security/logs': typeof ShellSecurityLogsRoute
  '/_shell/security/materials-handoff': typeof ShellSecurityMaterialsHandoffRoute
  '/_shell/security/motorcycle-log': typeof ShellSecurityMotorcycleLogRoute
  '/_shell/security/staff-attendance': typeof ShellSecurityStaffAttendanceRoute
  '/_shell/security/staff-movement': typeof ShellSecurityStaffMovementRoute
  '/_shell/security/suppliers': typeof ShellSecuritySuppliersRoute
  '/_shell/security/visitor-log': typeof ShellSecurityVisitorLogRoute
  '/_shell/settings/branches': typeof ShellSettingsBranchesRoute
  '/_shell/settings/org-settings': typeof ShellSettingsOrgSettingsRoute
  '/_shell/settings/profile': typeof ShellSettingsProfileRoute
  '/_shell/settings/rbac': typeof ShellSettingsRbacRoute
  '/_shell/settings/staff': typeof ShellSettingsStaffRoute
  '/_shell/settings/user-management': typeof ShellSettingsUserManagementRoute
  '/_shell/warehouse/alerts': typeof ShellWarehouseAlertsRoute
  '/_shell/warehouse/bin-card': typeof ShellWarehouseBinCardRoute
  '/_shell/warehouse/grn': typeof ShellWarehouseGrnRoute
  '/_shell/warehouse/production': typeof ShellWarehouseProductionRoute
  '/_shell/warehouse/stock-overview': typeof ShellWarehouseStockOverviewRoute
  '/_shell/finance/': typeof ShellFinanceIndexRoute
  '/_shell/logistics/': typeof ShellLogisticsIndexRoute
  '/_shell/security/': typeof ShellSecurityIndexRoute
  '/_shell/warehouse/': typeof ShellWarehouseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/finance'
    | '/logistics'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/security'
    | '/warehouse'
    | '/ceo/overview'
    | '/ceo/reports'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/overview'
    | '/finance/payroll'
    | '/finance/sales'
    | '/finance/supplier-payments'
    | '/logistics/drivers'
    | '/logistics/fleet'
    | '/logistics/maintenance'
    | '/logistics/trips'
    | '/logistics/waybills'
    | '/security/attendance-scanner'
    | '/security/dispatch'
    | '/security/gate-log'
    | '/security/item-bought'
    | '/security/labourers-log'
    | '/security/light-token'
    | '/security/logs'
    | '/security/materials-handoff'
    | '/security/motorcycle-log'
    | '/security/staff-attendance'
    | '/security/staff-movement'
    | '/security/suppliers'
    | '/security/visitor-log'
    | '/settings/branches'
    | '/settings/org-settings'
    | '/settings/profile'
    | '/settings/rbac'
    | '/settings/staff'
    | '/settings/user-management'
    | '/warehouse/alerts'
    | '/warehouse/bin-card'
    | '/warehouse/grn'
    | '/warehouse/production'
    | '/warehouse/stock-overview'
    | '/finance/'
    | '/logistics/'
    | '/security/'
    | '/warehouse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/notifications'
    | '/overview'
    | '/profile'
    | '/ceo/overview'
    | '/ceo/reports'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/overview'
    | '/finance/payroll'
    | '/finance/sales'
    | '/finance/supplier-payments'
    | '/logistics/drivers'
    | '/logistics/fleet'
    | '/logistics/maintenance'
    | '/logistics/trips'
    | '/logistics/waybills'
    | '/security/attendance-scanner'
    | '/security/dispatch'
    | '/security/gate-log'
    | '/security/item-bought'
    | '/security/labourers-log'
    | '/security/light-token'
    | '/security/logs'
    | '/security/materials-handoff'
    | '/security/motorcycle-log'
    | '/security/staff-attendance'
    | '/security/staff-movement'
    | '/security/suppliers'
    | '/security/visitor-log'
    | '/settings/branches'
    | '/settings/org-settings'
    | '/settings/profile'
    | '/settings/rbac'
    | '/settings/staff'
    | '/settings/user-management'
    | '/warehouse/alerts'
    | '/warehouse/bin-card'
    | '/warehouse/grn'
    | '/warehouse/production'
    | '/warehouse/stock-overview'
    | '/finance'
    | '/logistics'
    | '/security'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_shell'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/_shell/finance'
    | '/_shell/logistics'
    | '/_shell/notifications'
    | '/_shell/overview'
    | '/_shell/profile'
    | '/_shell/security'
    | '/_shell/warehouse'
    | '/_shell/ceo/overview'
    | '/_shell/ceo/reports'
    | '/_shell/finance/expenses'
    | '/_shell/finance/invoices'
    | '/_shell/finance/overview'
    | '/_shell/finance/payroll'
    | '/_shell/finance/sales'
    | '/_shell/finance/supplier-payments'
    | '/_shell/logistics/drivers'
    | '/_shell/logistics/fleet'
    | '/_shell/logistics/maintenance'
    | '/_shell/logistics/trips'
    | '/_shell/logistics/waybills'
    | '/_shell/security/attendance-scanner'
    | '/_shell/security/dispatch'
    | '/_shell/security/gate-log'
    | '/_shell/security/item-bought'
    | '/_shell/security/labourers-log'
    | '/_shell/security/light-token'
    | '/_shell/security/logs'
    | '/_shell/security/materials-handoff'
    | '/_shell/security/motorcycle-log'
    | '/_shell/security/staff-attendance'
    | '/_shell/security/staff-movement'
    | '/_shell/security/suppliers'
    | '/_shell/security/visitor-log'
    | '/_shell/settings/branches'
    | '/_shell/settings/org-settings'
    | '/_shell/settings/profile'
    | '/_shell/settings/rbac'
    | '/_shell/settings/staff'
    | '/_shell/settings/user-management'
    | '/_shell/warehouse/alerts'
    | '/_shell/warehouse/bin-card'
    | '/_shell/warehouse/grn'
    | '/_shell/warehouse/production'
    | '/_shell/warehouse/stock-overview'
    | '/_shell/finance/'
    | '/_shell/logistics/'
    | '/_shell/security/'
    | '/_shell/warehouse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  ShellRoute: typeof ShellRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/warehouse': {
      id: '/_shell/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof ShellWarehouseRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/security': {
      id: '/_shell/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof ShellSecurityRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/profile': {
      id: '/_shell/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ShellProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/overview': {
      id: '/_shell/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof ShellOverviewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/notifications': {
      id: '/_shell/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ShellNotificationsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/logistics': {
      id: '/_shell/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof ShellLogisticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/finance': {
      id: '/_shell/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof ShellFinanceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/warehouse/': {
      id: '/_shell/warehouse/'
      path: '/'
      fullPath: '/warehouse/'
      preLoaderRoute: typeof ShellWarehouseIndexRouteImport
      parentRoute: typeof ShellWarehouseRoute
    }
    '/_shell/security/': {
      id: '/_shell/security/'
      path: '/'
      fullPath: '/security/'
      preLoaderRoute: typeof ShellSecurityIndexRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/logistics/': {
      id: '/_shell/logistics/'
      path: '/'
      fullPath: '/logistics/'
      preLoaderRoute: typeof ShellLogisticsIndexRouteImport
      parentRoute: typeof ShellLogisticsRoute
    }
    '/_shell/finance/': {
      id: '/_shell/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof ShellFinanceIndexRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/warehouse/stock-overview': {
      id: '/_shell/warehouse/stock-overview'
      path: '/stock-overview'
      fullPath: '/warehouse/stock-overview'
      preLoaderRoute: typeof ShellWarehouseStockOverviewRouteImport
      parentRoute: typeof ShellWarehouseRoute
    }
    '/_shell/warehouse/production': {
      id: '/_shell/warehouse/production'
      path: '/production'
      fullPath: '/warehouse/production'
      preLoaderRoute: typeof ShellWarehouseProductionRouteImport
      parentRoute: typeof ShellWarehouseRoute
    }
    '/_shell/warehouse/grn': {
      id: '/_shell/warehouse/grn'
      path: '/grn'
      fullPath: '/warehouse/grn'
      preLoaderRoute: typeof ShellWarehouseGrnRouteImport
      parentRoute: typeof ShellWarehouseRoute
    }
    '/_shell/warehouse/bin-card': {
      id: '/_shell/warehouse/bin-card'
      path: '/bin-card'
      fullPath: '/warehouse/bin-card'
      preLoaderRoute: typeof ShellWarehouseBinCardRouteImport
      parentRoute: typeof ShellWarehouseRoute
    }
    '/_shell/warehouse/alerts': {
      id: '/_shell/warehouse/alerts'
      path: '/alerts'
      fullPath: '/warehouse/alerts'
      preLoaderRoute: typeof ShellWarehouseAlertsRouteImport
      parentRoute: typeof ShellWarehouseRoute
    }
    '/_shell/settings/user-management': {
      id: '/_shell/settings/user-management'
      path: '/settings/user-management'
      fullPath: '/settings/user-management'
      preLoaderRoute: typeof ShellSettingsUserManagementRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/staff': {
      id: '/_shell/settings/staff'
      path: '/settings/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof ShellSettingsStaffRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/rbac': {
      id: '/_shell/settings/rbac'
      path: '/settings/rbac'
      fullPath: '/settings/rbac'
      preLoaderRoute: typeof ShellSettingsRbacRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/profile': {
      id: '/_shell/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ShellSettingsProfileRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/org-settings': {
      id: '/_shell/settings/org-settings'
      path: '/settings/org-settings'
      fullPath: '/settings/org-settings'
      preLoaderRoute: typeof ShellSettingsOrgSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/branches': {
      id: '/_shell/settings/branches'
      path: '/settings/branches'
      fullPath: '/settings/branches'
      preLoaderRoute: typeof ShellSettingsBranchesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/security/visitor-log': {
      id: '/_shell/security/visitor-log'
      path: '/visitor-log'
      fullPath: '/security/visitor-log'
      preLoaderRoute: typeof ShellSecurityVisitorLogRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/suppliers': {
      id: '/_shell/security/suppliers'
      path: '/suppliers'
      fullPath: '/security/suppliers'
      preLoaderRoute: typeof ShellSecuritySuppliersRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/staff-movement': {
      id: '/_shell/security/staff-movement'
      path: '/staff-movement'
      fullPath: '/security/staff-movement'
      preLoaderRoute: typeof ShellSecurityStaffMovementRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/staff-attendance': {
      id: '/_shell/security/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/security/staff-attendance'
      preLoaderRoute: typeof ShellSecurityStaffAttendanceRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/motorcycle-log': {
      id: '/_shell/security/motorcycle-log'
      path: '/motorcycle-log'
      fullPath: '/security/motorcycle-log'
      preLoaderRoute: typeof ShellSecurityMotorcycleLogRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/materials-handoff': {
      id: '/_shell/security/materials-handoff'
      path: '/materials-handoff'
      fullPath: '/security/materials-handoff'
      preLoaderRoute: typeof ShellSecurityMaterialsHandoffRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/logs': {
      id: '/_shell/security/logs'
      path: '/logs'
      fullPath: '/security/logs'
      preLoaderRoute: typeof ShellSecurityLogsRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/light-token': {
      id: '/_shell/security/light-token'
      path: '/light-token'
      fullPath: '/security/light-token'
      preLoaderRoute: typeof ShellSecurityLightTokenRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/labourers-log': {
      id: '/_shell/security/labourers-log'
      path: '/labourers-log'
      fullPath: '/security/labourers-log'
      preLoaderRoute: typeof ShellSecurityLabourersLogRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/item-bought': {
      id: '/_shell/security/item-bought'
      path: '/item-bought'
      fullPath: '/security/item-bought'
      preLoaderRoute: typeof ShellSecurityItemBoughtRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/gate-log': {
      id: '/_shell/security/gate-log'
      path: '/gate-log'
      fullPath: '/security/gate-log'
      preLoaderRoute: typeof ShellSecurityGateLogRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/dispatch': {
      id: '/_shell/security/dispatch'
      path: '/dispatch'
      fullPath: '/security/dispatch'
      preLoaderRoute: typeof ShellSecurityDispatchRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/security/attendance-scanner': {
      id: '/_shell/security/attendance-scanner'
      path: '/attendance-scanner'
      fullPath: '/security/attendance-scanner'
      preLoaderRoute: typeof ShellSecurityAttendanceScannerRouteImport
      parentRoute: typeof ShellSecurityRoute
    }
    '/_shell/logistics/waybills': {
      id: '/_shell/logistics/waybills'
      path: '/waybills'
      fullPath: '/logistics/waybills'
      preLoaderRoute: typeof ShellLogisticsWaybillsRouteImport
      parentRoute: typeof ShellLogisticsRoute
    }
    '/_shell/logistics/trips': {
      id: '/_shell/logistics/trips'
      path: '/trips'
      fullPath: '/logistics/trips'
      preLoaderRoute: typeof ShellLogisticsTripsRouteImport
      parentRoute: typeof ShellLogisticsRoute
    }
    '/_shell/logistics/maintenance': {
      id: '/_shell/logistics/maintenance'
      path: '/maintenance'
      fullPath: '/logistics/maintenance'
      preLoaderRoute: typeof ShellLogisticsMaintenanceRouteImport
      parentRoute: typeof ShellLogisticsRoute
    }
    '/_shell/logistics/fleet': {
      id: '/_shell/logistics/fleet'
      path: '/fleet'
      fullPath: '/logistics/fleet'
      preLoaderRoute: typeof ShellLogisticsFleetRouteImport
      parentRoute: typeof ShellLogisticsRoute
    }
    '/_shell/logistics/drivers': {
      id: '/_shell/logistics/drivers'
      path: '/drivers'
      fullPath: '/logistics/drivers'
      preLoaderRoute: typeof ShellLogisticsDriversRouteImport
      parentRoute: typeof ShellLogisticsRoute
    }
    '/_shell/finance/supplier-payments': {
      id: '/_shell/finance/supplier-payments'
      path: '/supplier-payments'
      fullPath: '/finance/supplier-payments'
      preLoaderRoute: typeof ShellFinanceSupplierPaymentsRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/finance/sales': {
      id: '/_shell/finance/sales'
      path: '/sales'
      fullPath: '/finance/sales'
      preLoaderRoute: typeof ShellFinanceSalesRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/finance/payroll': {
      id: '/_shell/finance/payroll'
      path: '/payroll'
      fullPath: '/finance/payroll'
      preLoaderRoute: typeof ShellFinancePayrollRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/finance/overview': {
      id: '/_shell/finance/overview'
      path: '/overview'
      fullPath: '/finance/overview'
      preLoaderRoute: typeof ShellFinanceOverviewRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/finance/invoices': {
      id: '/_shell/finance/invoices'
      path: '/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof ShellFinanceInvoicesRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/finance/expenses': {
      id: '/_shell/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof ShellFinanceExpensesRouteImport
      parentRoute: typeof ShellFinanceRoute
    }
    '/_shell/ceo/reports': {
      id: '/_shell/ceo/reports'
      path: '/ceo/reports'
      fullPath: '/ceo/reports'
      preLoaderRoute: typeof ShellCeoReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/ceo/overview': {
      id: '/_shell/ceo/overview'
      path: '/ceo/overview'
      fullPath: '/ceo/overview'
      preLoaderRoute: typeof ShellCeoOverviewRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellFinanceRouteChildren {
  ShellFinanceExpensesRoute: typeof ShellFinanceExpensesRoute
  ShellFinanceInvoicesRoute: typeof ShellFinanceInvoicesRoute
  ShellFinanceOverviewRoute: typeof ShellFinanceOverviewRoute
  ShellFinancePayrollRoute: typeof ShellFinancePayrollRoute
  ShellFinanceSalesRoute: typeof ShellFinanceSalesRoute
  ShellFinanceSupplierPaymentsRoute: typeof ShellFinanceSupplierPaymentsRoute
  ShellFinanceIndexRoute: typeof ShellFinanceIndexRoute
}

const ShellFinanceRouteChildren: ShellFinanceRouteChildren = {
  ShellFinanceExpensesRoute: ShellFinanceExpensesRoute,
  ShellFinanceInvoicesRoute: ShellFinanceInvoicesRoute,
  ShellFinanceOverviewRoute: ShellFinanceOverviewRoute,
  ShellFinancePayrollRoute: ShellFinancePayrollRoute,
  ShellFinanceSalesRoute: ShellFinanceSalesRoute,
  ShellFinanceSupplierPaymentsRoute: ShellFinanceSupplierPaymentsRoute,
  ShellFinanceIndexRoute: ShellFinanceIndexRoute,
}

const ShellFinanceRouteWithChildren = ShellFinanceRoute._addFileChildren(
  ShellFinanceRouteChildren,
)

interface ShellLogisticsRouteChildren {
  ShellLogisticsDriversRoute: typeof ShellLogisticsDriversRoute
  ShellLogisticsFleetRoute: typeof ShellLogisticsFleetRoute
  ShellLogisticsMaintenanceRoute: typeof ShellLogisticsMaintenanceRoute
  ShellLogisticsTripsRoute: typeof ShellLogisticsTripsRoute
  ShellLogisticsWaybillsRoute: typeof ShellLogisticsWaybillsRoute
  ShellLogisticsIndexRoute: typeof ShellLogisticsIndexRoute
}

const ShellLogisticsRouteChildren: ShellLogisticsRouteChildren = {
  ShellLogisticsDriversRoute: ShellLogisticsDriversRoute,
  ShellLogisticsFleetRoute: ShellLogisticsFleetRoute,
  ShellLogisticsMaintenanceRoute: ShellLogisticsMaintenanceRoute,
  ShellLogisticsTripsRoute: ShellLogisticsTripsRoute,
  ShellLogisticsWaybillsRoute: ShellLogisticsWaybillsRoute,
  ShellLogisticsIndexRoute: ShellLogisticsIndexRoute,
}

const ShellLogisticsRouteWithChildren = ShellLogisticsRoute._addFileChildren(
  ShellLogisticsRouteChildren,
)

interface ShellSecurityRouteChildren {
  ShellSecurityAttendanceScannerRoute: typeof ShellSecurityAttendanceScannerRoute
  ShellSecurityDispatchRoute: typeof ShellSecurityDispatchRoute
  ShellSecurityGateLogRoute: typeof ShellSecurityGateLogRoute
  ShellSecurityItemBoughtRoute: typeof ShellSecurityItemBoughtRoute
  ShellSecurityLabourersLogRoute: typeof ShellSecurityLabourersLogRoute
  ShellSecurityLightTokenRoute: typeof ShellSecurityLightTokenRoute
  ShellSecurityLogsRoute: typeof ShellSecurityLogsRoute
  ShellSecurityMaterialsHandoffRoute: typeof ShellSecurityMaterialsHandoffRoute
  ShellSecurityMotorcycleLogRoute: typeof ShellSecurityMotorcycleLogRoute
  ShellSecurityStaffAttendanceRoute: typeof ShellSecurityStaffAttendanceRoute
  ShellSecurityStaffMovementRoute: typeof ShellSecurityStaffMovementRoute
  ShellSecuritySuppliersRoute: typeof ShellSecuritySuppliersRoute
  ShellSecurityVisitorLogRoute: typeof ShellSecurityVisitorLogRoute
  ShellSecurityIndexRoute: typeof ShellSecurityIndexRoute
}

const ShellSecurityRouteChildren: ShellSecurityRouteChildren = {
  ShellSecurityAttendanceScannerRoute: ShellSecurityAttendanceScannerRoute,
  ShellSecurityDispatchRoute: ShellSecurityDispatchRoute,
  ShellSecurityGateLogRoute: ShellSecurityGateLogRoute,
  ShellSecurityItemBoughtRoute: ShellSecurityItemBoughtRoute,
  ShellSecurityLabourersLogRoute: ShellSecurityLabourersLogRoute,
  ShellSecurityLightTokenRoute: ShellSecurityLightTokenRoute,
  ShellSecurityLogsRoute: ShellSecurityLogsRoute,
  ShellSecurityMaterialsHandoffRoute: ShellSecurityMaterialsHandoffRoute,
  ShellSecurityMotorcycleLogRoute: ShellSecurityMotorcycleLogRoute,
  ShellSecurityStaffAttendanceRoute: ShellSecurityStaffAttendanceRoute,
  ShellSecurityStaffMovementRoute: ShellSecurityStaffMovementRoute,
  ShellSecuritySuppliersRoute: ShellSecuritySuppliersRoute,
  ShellSecurityVisitorLogRoute: ShellSecurityVisitorLogRoute,
  ShellSecurityIndexRoute: ShellSecurityIndexRoute,
}

const ShellSecurityRouteWithChildren = ShellSecurityRoute._addFileChildren(
  ShellSecurityRouteChildren,
)

interface ShellWarehouseRouteChildren {
  ShellWarehouseAlertsRoute: typeof ShellWarehouseAlertsRoute
  ShellWarehouseBinCardRoute: typeof ShellWarehouseBinCardRoute
  ShellWarehouseGrnRoute: typeof ShellWarehouseGrnRoute
  ShellWarehouseProductionRoute: typeof ShellWarehouseProductionRoute
  ShellWarehouseStockOverviewRoute: typeof ShellWarehouseStockOverviewRoute
  ShellWarehouseIndexRoute: typeof ShellWarehouseIndexRoute
}

const ShellWarehouseRouteChildren: ShellWarehouseRouteChildren = {
  ShellWarehouseAlertsRoute: ShellWarehouseAlertsRoute,
  ShellWarehouseBinCardRoute: ShellWarehouseBinCardRoute,
  ShellWarehouseGrnRoute: ShellWarehouseGrnRoute,
  ShellWarehouseProductionRoute: ShellWarehouseProductionRoute,
  ShellWarehouseStockOverviewRoute: ShellWarehouseStockOverviewRoute,
  ShellWarehouseIndexRoute: ShellWarehouseIndexRoute,
}

const ShellWarehouseRouteWithChildren = ShellWarehouseRoute._addFileChildren(
  ShellWarehouseRouteChildren,
)

interface ShellRouteChildren {
  ShellFinanceRoute: typeof ShellFinanceRouteWithChildren
  ShellLogisticsRoute: typeof ShellLogisticsRouteWithChildren
  ShellNotificationsRoute: typeof ShellNotificationsRoute
  ShellOverviewRoute: typeof ShellOverviewRoute
  ShellProfileRoute: typeof ShellProfileRoute
  ShellSecurityRoute: typeof ShellSecurityRouteWithChildren
  ShellWarehouseRoute: typeof ShellWarehouseRouteWithChildren
  ShellCeoOverviewRoute: typeof ShellCeoOverviewRoute
  ShellCeoReportsRoute: typeof ShellCeoReportsRoute
  ShellSettingsBranchesRoute: typeof ShellSettingsBranchesRoute
  ShellSettingsOrgSettingsRoute: typeof ShellSettingsOrgSettingsRoute
  ShellSettingsProfileRoute: typeof ShellSettingsProfileRoute
  ShellSettingsRbacRoute: typeof ShellSettingsRbacRoute
  ShellSettingsStaffRoute: typeof ShellSettingsStaffRoute
  ShellSettingsUserManagementRoute: typeof ShellSettingsUserManagementRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellFinanceRoute: ShellFinanceRouteWithChildren,
  ShellLogisticsRoute: ShellLogisticsRouteWithChildren,
  ShellNotificationsRoute: ShellNotificationsRoute,
  ShellOverviewRoute: ShellOverviewRoute,
  ShellProfileRoute: ShellProfileRoute,
  ShellSecurityRoute: ShellSecurityRouteWithChildren,
  ShellWarehouseRoute: ShellWarehouseRouteWithChildren,
  ShellCeoOverviewRoute: ShellCeoOverviewRoute,
  ShellCeoReportsRoute: ShellCeoReportsRoute,
  ShellSettingsBranchesRoute: ShellSettingsBranchesRoute,
  ShellSettingsOrgSettingsRoute: ShellSettingsOrgSettingsRoute,
  ShellSettingsProfileRoute: ShellSettingsProfileRoute,
  ShellSettingsRbacRoute: ShellSettingsRbacRoute,
  ShellSettingsStaffRoute: ShellSettingsStaffRoute,
  ShellSettingsUserManagementRoute: ShellSettingsUserManagementRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  ShellRoute: ShellRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
